title: Ivaylo Getov Dot Com
timezone: America/Los_Angeles
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivaylogetov.com" # the base hostname & protocol for your site
twitter_username: ivaylopg
github_username:  ivaylopg
sass:
  style: compressed
permalink: /:slug
google_analytics: 15828180-1
exclude:
- node_modules
- siteleaf-gem
- ".gitignore"
- package.json
- Gemfile
- Gemfile.lock
- ivaylogetov.sublime-project
- ivaylogetov.sublime-workspace
- old

# Build settings
markdown: kramdown
