title: Ivaylo Getov Dot Com
timezone: America/Los_Angeles
description: > # this means to ignore newlines until "baseurl:"
  Hi. I'm Ivaylo Getov. I’m a cofounder and Creative Director at Luxloop,
  a creative-technology studio. I make interactive art using technology.
  I’d love to talk to you."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivaylogetov.com" # the base hostname & protocol for your site
twitter_username: ivaylopg
github_username:  ivaylopg
sass:
  style: compressed
permalink: /:slug
google_analytics: 15828180-1
exclude:
- node_modules
- siteleaf-gem
- ".gitignore"
- package.json
- Gemfile
- Gemfile.lock
- ivaylogetov.sublime-project
- ivaylogetov.sublime-workspace
- gulpfile.js

# Build settings
markdown: kramdown

kramdown:
   input: GFM
   hard_wrap: true
